// Shared translations for the administrative UI; user-provided content is never translated.
export const insightsEnglish: Record<string, string> = {
  '管理密钥无效，请检查后再试。': 'Invalid admin key. Check it and try again.',
  '请检查日期与筛选条件：日期限最近 90 天，小时明细最多查看 7 天。':
    'Check the dates and filters. Data is available for the last 90 days; hourly detail supports up to seven days.',
  '查询较频繁，请稍后再试。': 'Too many queries. Please try again shortly.',
  '统计暂时不可用，已保留上次结果。':
    'Analytics is temporarily unavailable. Your previous results are still shown.',
  '查询超时，已保留上次结果，请稍后重试。':
    'The query timed out. Your previous results are still shown. Please try again.',
  加载失败: 'Could not load data',
  打开旧版引导: 'Opened legacy guide',
  '旧版：返回选择主题': 'Legacy: returned to topics',
  '旧版：进入目标选择': 'Legacy: opened goals',
  '旧版：进入补充与预览': 'Legacy: opened details and preview',
  '旧版：切换直接输入': 'Legacy: switched to direct input',
  '旧版：引导内容放入草稿': 'Legacy: created a draft',
  选择澄清回答: 'Selected a clarification answer',
  选择继续追问: 'Selected a follow-up',
  从引导开始对话: 'Started from a suggestion',
  回复澄清问题: 'Answered a clarification',
  发送后续追问: 'Sent a follow-up',
  发送示例提问: 'Sent an example question',
  访问者类型: 'Visitor type',
  客户端标识: 'Client identity',
  请求用途: 'Request purpose',
  分类依据: 'Classification evidence',
  资源类型: 'Resource type',
  请求方法: 'HTTP method',
  引荐来源: 'Referral source',
  渠道类型: 'Medium',
  推广活动: 'Campaign',
  浏览页面: 'Page',
  进入页面: 'Entry page',
  语言: 'Language',
  设备: 'Device',
  浏览器: 'Browser',
  操作系统: 'Operating system',
  '国家 / 地区': 'Country / region',
  使用方式: 'Channel',
  工具: 'Tool',
  'Agent 模式': 'Agent mode',
  入口点击: 'Entry point click',
  全部: 'All',
  访问与使用: 'Traffic & usage',
  '看见每个时段的变化，再沿着来源、页面与功能继续探索。':
    'Explore changes over time, then look closer at sources, pages and product use.',
  仅管理员可见: 'Admin access only',
  打开数据观察室: 'Open the observatory',
  '输入管理密钥查看统计。密钥仅用于本页请求，不写入网址或浏览器存储。':
    'Enter your admin key to view analytics. It is used only for requests from this page and is never saved in the URL or browser storage.',
  管理密钥: 'Admin key',
  '正在准备面板…': 'Preparing…',
  '正在验证…': 'Verifying…',
  查看统计: 'View analytics',
  数据视图: 'Data views',
  使用概览: 'Overview',
  使用历史: 'Usage history',
  用户反馈: 'Feedback',
  历史归档: 'Archives',
  退出: 'Sign out',
  统计时间范围: 'Reporting period',
  天: ' days',
  自定义: 'Custom',
  时区: 'Time zone',
  '北京 · UTC+8': 'Beijing · UTC+8',
  曲线粒度: 'Interval',
  自动: 'Automatic',
  '按小时（≤7 天）': 'Hourly (up to 7 days)',
  按天: 'Daily',
  开始日期: 'Start date',
  至: 'to',
  结束日期: 'End date',
  '包含起止日期，最多 90 天。': 'Both dates are included. Up to 90 days.',
  统计人群: 'Audience',
  '浏览器（含兼容旧记录）': 'Browsers (including legacy records)',
  更多筛选: 'More filters',
  '客户端、依据、资源、设备与渠道等': 'Clients, evidence, resources, devices and channels',
  '国家 / 地区代码': 'Country / region code',
  '例如 CN、US': 'e.g. CN, US',
  '“功能事件”只保留该功能的操作记录。查看某个工具页的访问量，可使用“浏览页面”筛选。':
    'The feature filter includes only events tagged with that feature. Use the page filter to measure visits to a tool page.',
  包含测试流量: 'Include test traffic',
  '筛选已修改，应用后更新图表': 'Filters changed. Apply them to update the charts.',
  全部图表使用同一组筛选: 'All charts use the same applied filters.',
  重置: 'Reset',
  '读取中…': 'Loading…',
  应用筛选: 'Apply filters',
  北京时间: 'Beijing time',
  含测试流量: 'Includes test traffic',
  已排除测试: 'Test traffic excluded',
  数据截至: 'Data as of ',
  '导出汇总 JSON': 'Export summary JSON',
  曲线已显示: 'Shown on chart',
  点击显示曲线: 'Show on chart',
  '当前筛选下还没有记录。可以扩大时间范围或移除筛选条件；图表不会填入演示数据。':
    'No records match these filters. Try a longer period or remove a filter. Charts never substitute demo data.',
  统计口径与分类覆盖: 'Measurement and classification coverage',
  '浏览、抓取与调用，分别计数': 'Visits, content requests and service calls',
  '浏览器页面浏览来自网页事件，排除已识别自动化；内容请求来自服务端 GET，包含网页、手册和发现文件，不计入浏览量或访客数。服务调用排除内部工具阶段，MCP tools/call 每次计一次，初始化与列表请求不计。问卜 Agent 完成是产品功能指标。':
    'Browser pageviews come from client events and exclude identified automation. Server-side content GET requests include pages, guides and discovery files, but do not count as pageviews or visitors. Each MCP tools/call counts once; initialization, tool listings and internal Agent stages are excluded from service calls. Completed Wenbu Agent turns are a separate product metric.',
  新分类事件: ' newly classified events',
  '旧记录，无细分类依据': ' legacy events without detailed evidence',
  '自动化或未知浏览事件，未计 PV': ' automated or unknown views excluded from PV',
  未识别内容请求: ' unclassified content requests',
  'CF 验证自动化请求': ' Cloudflare-verified automated requests',
  'CF 签名 Agent 请求': ' Cloudflare-signed Agent requests',
  'UA 和协议可伪装；浏览器特征不保证真人。Cloudflare 验证只在边缘提供依据时标记，具体名称仍来自 UA。旧的非 bot 网页记录保留在浏览指标中；历史抓取量无法补算，升级前缺少收尾记录的 MCP 调用也无法可靠补算。请求统计不覆盖边缘拦截、资源文件或后台页面。':
    'User agents and protocols can be spoofed; browser signals do not prove a human visit. Cloudflare verification is recorded only when supplied by the edge; client names still come from user agents. Legacy non-bot page events remain in browsing metrics. Earlier crawls and MCP calls without completion records cannot be reliably reconstructed. These counts exclude edge-blocked requests, assets and admin pages.',
  使用与数据质量: 'Usage and data quality',
  完成使用与采集质量: 'Completed use and collection quality',
  完成使用的浏览器标识: 'Browser IDs with completed use',
  '个 · 关联会话': ' · linked sessions ',
  '个。由服务器确认成功结果，排除示例；标识不是自然人数，自动化不能仅靠 UA 完全识别。':
    '. Successful results are server-confirmed and exclude examples. Identifiers are not people; user agents alone cannot identify all automation.',
  客户端: 'Client events: ',
  条: ' records',
  服务端: 'Server events: ',
  内容请求: 'Content requests',
  时间校正: 'Adjusted timestamps: ',
  '延迟超过 5 分钟': 'Delayed over 5 minutes: ',
  未关联标识的成功: 'Successes without linked IDs: ',
  次: ' events',
  客户端报告丢弃: 'Client-reported dropped events',
  '只反映已收到记录；没有记录不等于没有丢失。隐私退出、脚本阻止和边缘拦截不在覆盖范围内。标记测试的事件默认排除，未标记的自测无法事后可靠识别。工具筛选只保留带该工具标签的事件，可能没有 PV，不能据此计算转化率。':
    'Coverage reflects received records only; missing records do not prove no data was lost. Opt-outs, blocked scripts and edge blocks are outside coverage. Marked tests are excluded by default; unmarked tests cannot be reliably identified later. Feature filters can exclude pageviews, so their results should not be used as a conversion denominator.',
  查看全部指标定义与版本: 'All metric definitions and version',
  '口径版本：': 'Measurement version: ',
  旧版: 'Legacy',
  '。浏览器标识和会话按完整范围去重，每小时 / 每天数字不能相加得到整体人数。':
    '. Browser IDs and sessions are deduplicated across the full period. Hourly or daily counts cannot be added to obtain the overall total.',
  示例计算: 'Example calculations: ',
  '次 · 输入未通过': ' · invalid inputs: ',
  '次 · 额度 / 限速': ' · quota / rate limits: ',
  '次 · 用户中断': ' · user cancellations: ',
  '次 · Agent 等待补充': ' · Agent turns awaiting input: ',
  '回合。与服务错误分开统计。': '. Counted separately from service errors.',
  展开详细统计表: 'Detailed tables',
  '来源、引导、性能与全部事件': 'Sources, guidance, performance and events',
  'Agent 提问引导': 'Agent conversation guidance',
  '只统计步骤与操作类型，不记录选择内容。发送表示发起回合，不等同于服务端完成；不是严格漏斗。':
    'Only steps and action types are counted, never answer contents. Sending starts a turn; it does not confirm completion. This is not a strict funnel.',
  操作: 'Action',
  次数: 'Count',
  会话: 'Sessions',
  '所选范围内还没有引导事件。': 'No guidance events in this period.',
  '自由修改后不再包含原建议的发送归为普通对话；不推断用户主题或个人特征。':
    'A rewritten suggestion is treated as an ordinary message when the original is no longer present. Topics and personal traits are not inferred.',
  维度: 'Dimension',
  事件: 'Event',
  浏览量: 'Pageviews',
  '内容 GET': 'Content GETs',
  服务调用: 'Service calls',
  成功: 'Successes',
  服务状态与耗时: 'Service outcomes and duration',
  功能: 'Feature',
  状态: 'Status',
  平均耗时: 'Average duration',
  最大耗时: 'Maximum duration',
  全部事件与接收位置: 'All events and collection points',
  接收位置: 'Collection point',
  数量: 'Count',
  '近 N 天包含今天，按所选时区的自然日分组，今天仍在变化。匿名访客是 30 天有效的浏览器标识，不等于自然人数。拦截、关闭统计和延迟补发会影响覆盖；0 表示未记录到事件。服务端请求只记录公开内容路径、粗略类别和响应状态，不创建访客身份。最近 90 天明细可在线查看，更早记录从私有归档导出。数据用于产品改进，不用于计费。':
    'The last N days include today, grouped by calendar day in the selected time zone. Today is still in progress. Anonymous visitors are browser identifiers valid for 30 days, not individual people. Blocking, opt-outs and delayed events affect coverage; zero means no event was recorded. Server requests contain public path categories, coarse classifications and response status, without visitor identities. The latest 90 days are available online; older data can be exported from private archives. These reports support product improvement, not billing.',
  ' 起的一小时': ' — one hour starting here',
  '尚未结束 · 截至': 'In progress · as of ',
  '时段开始 UTC': 'Period start UTC',
  '时段结束 UTC': 'Period end UTC',
  统计时区: 'Reporting time zone',
  '数据截至 UTC': 'Data as of UTC',
  '已应用筛选 JSON': 'Applied filters JSON',
  访问与使用趋势: 'Traffic and usage over time',
  每小时: 'Hourly',
  每天: 'Daily',
  '一个观测点 ·': ' observations · ',
  '北京时间 UTC+8': 'Beijing time UTC+8',
  查看曲线: 'Show chart',
  查看数据: 'Show data',
  '导出 CSV': 'Export CSV',
  显示的趋势指标: 'Visible metrics',
  '相同筛选下的完整趋势数据；时段按所选时区显示':
    'Complete trend data for the applied filters, in the selected time zone',
  时段: 'Period',
  尚未到来: 'Future',
  进行中: 'In progress',
  已结束: 'Finished',
  '悬停或使用左右方向键查看数值。空白时段尚未到来；0 表示该时段未记录到事件。当前时段未结束。访客与会话在每个时段内去重，跨时段不能直接相加。':
    'Hover or use the left and right arrow keys to inspect values. Blank periods are in the future; zero means no event was recorded. The current period is incomplete. Visitors and sessions are deduplicated within each period and cannot be added across periods.',
  '当前筛选下暂无记录。': 'No records match these filters.',
  收起: 'Show less',
  比例以当前筛选下的: 'Shares use the filtered total for ',
  '为分母。': ' as the denominator. ',
  '点击名称进一步筛选。': 'Select a name to filter further.',
  '抓取与 Agent 流量分类': 'Crawler and Agent traffic',
  谁在请求内容: 'Who is requesting content?',
  '以下分布只使用内容 GET 请求；同一次请求只属于一个类型。':
    'These distributions count content GET requests only. Each request belongs to one type.',
  客户端与抓取用途: 'Clients and crawlers',
  '搜索、训练与用户委托': 'Search, training and user requests',
  被读取的内容形式: 'Content formats requested',
  内容响应状态: 'Content response status',
  '包含重定向与失败，HEAD 单独列示，不计入内容 GET 曲线。':
    'Includes redirects and failures. HEAD requests are listed separately and excluded from GET trends.',
  方法: 'Method',
  请求数: 'Requests',
  '当前筛选下暂无内容请求。': 'No content requests match these filters.',
  访问从哪里来: 'Where visits come from',
  页面浏览: 'Pageviews',
  哪些页面被看见: 'Which pages people view',
  '24 小时活跃分布': 'Activity across 24 hours',
  '将所选日期的页面浏览按钟点累加，观察活跃时段。':
    'Pageviews across the selected dates, grouped by hour of day. ',
  使用设备: 'Devices',
  完成了哪些功能: 'Completed features',
  '完成调用（含示例）': 'Completed calls (including examples)',
  服务结果分布: 'Service outcomes',
  会话走到了哪一步: 'How far sessions progress',
  '同一会话内逐层满足这些条件，不表示严格发生顺序。':
    'Each step satisfies all earlier conditions within a session. This does not imply a strict sequence.',
  访问页面: 'Visited a page',
  开始工具或对话: 'Started a tool or chat',
  实际完成: 'Completed an operation',
  保存为手记: 'Saved to journal',
  '比例以本范围内有访问记录的会话为分母。示例计算不算完成；无会话 ID 的 API / CLI / MCP 请求不计入。':
    'Shares use sessions with a pageview in this period as the denominator. Example calculations do not count as completion. API, CLI and MCP requests without session IDs are excluded.',
  待查看: 'New',
  处理中: 'In review',
  已解决: 'Resolved',
  已归档: 'Archived',
  '管理凭据已失效，请退出后重新登录。': 'Admin credentials have expired. Sign out and try again.',
  '请求较频繁，请稍后再试。': 'Too many requests. Please try again shortly.',
  '这条反馈已被更新，请重新打开。': 'This feedback has changed. Open it again to see the latest version.',
  '从一次操作，看见整个过程': 'Follow an operation from start to finish',
  '听见用户，跟进改进': 'Listen, review and improve',
  '历史数据，有据可查': 'An archive you can trace',
  '按实际发生时间倒序排列。点击会话或操作标识，查看相关事件；旧版事件可能没有关联标识。':
    'Newest events first, ordered by when they happened. Select a session or operation ID to see related events. Older events may lack linking identifiers.',
  '反馈、评价和处理状态集中在这里。主动分享的摘录与联系邮箱仅在展开详情时读取。':
    'Ratings, feedback and review status are collected here. Shared excerpts and contact email addresses are loaded only when you open the details.',
  '超过一天的事件按小时归档到私有 R2。D1 保留最近 90 天明细；归档未成功的记录不会因到期被删除。':
    'Events older than a day are archived hourly to private R2 storage. D1 retains the latest 90 days. Records are not removed on expiry unless archiving succeeds.',
  '已继承概览的时间、人群与维度筛选。':
    'Time, audience and dimension filters were carried over from the overview. ',
  '自然日与概览使用同一统计时区。': 'Calendar dates use the same reporting time zone as the overview. ',
  '人群：': ' Audience: ',
  '。导出只含本页，不代表全部历史。': '. Export includes this page only, not the full history.',
  '条在线事件（含测试）': ' online events (including tests)',
  '条已归档（含测试）': ' archived events (including tests)',
  '待归档：': 'Awaiting archive: ',
  '条（含当天）': ' events (including today)',
  条待看反馈: ' unread feedback items',
  归档未配置: 'Archiving is not configured',
  '最近归档失败 · 原始记录仍保留': 'Last archive failed · original records retained',
  '最近归档：': 'Last archive: ',
  等待首次归档: 'Waiting for the first archive',
  时间范围: 'Time range',
  自定义日期范围: 'Custom date range',
  '最近 10 年': 'Last 10 years',
  来源: 'Source',
  '更多维度：事件、依据、资源、设备与渠道':
    'More dimensions: events, evidence, resources, devices and channels',
  结果: 'Outcome',
  活动: 'Campaign',
  处理状态: 'Review status',
  '关联会话、操作、对话或浏览器标识': 'Link a session, operation, conversation or browser ID',
  '会话 ID': 'Session ID',
  '操作 ID': 'Operation ID',
  '对话 ID': 'Conversation ID',
  '访客 ID': 'Visitor ID',
  包含测试数据: 'Include test data',
  查询: 'Search',
  明细已应用筛选: 'Applied detail filters',
  完整归档文件: 'Complete archive files',
  包含测试: 'Includes tests',
  '正在读取…': 'Loading…',
  回到最新: 'Latest records',
  导出本页: 'Export this page',
  '这个范围内还没有记录。': 'No records in this range.',
  '可调整时间、筛选项，或勾选测试数据检查接入情况。':
    'Adjust the dates or filters, or include test data to check collection.',
  服务端操作: 'Server operation',
  服务端请求: 'Server request',
  网页事件: 'Web event',
  一条新建议: 'A new suggestion',
  有帮助: 'Helpful',
  还有提升空间: 'Could be better',
  没帮到我: 'Not helpful',
  '用户留下了评价。': 'The user left a rating.',
  'KB · NDJSON · SHA-256 已记录': 'KB · NDJSON · SHA-256 recorded',
  对话: 'Conversation',
  访客: 'Visitor',
  下载原始记录: 'Download original records',
  查看详情: 'View details',
  更早的记录: 'Older records',
  记录详情: 'Record details',
  反馈详情: 'Feedback details',
  事件详情: 'Event details',
  '收起 ×': 'Close ×',
  '仅评价，无补充文字。': 'Rating only; no written feedback.',
  '联系邮箱：': 'Contact email: ',
  用户主动分享的摘录: 'Excerpt shared by the user',
  查看这次操作的使用历史: 'Usage history for this operation',
  查看这次操作的反馈: 'Feedback for this operation',
  '事件使用随机标识关联，不代表实名用户。此处导出当前页；完整分页导出与归档重建方法见项目 docs/analytics.md。归档文件包含测试事件，请按 is_test 筛选；历史合并按事件 id 去重。':
    'Events are linked with random IDs, not real-world identities. This export covers the current page. For paginated exports and archive reconstruction, see docs/analytics.md in the project. Archive files include test events; filter by is_test and deduplicate merged history by event id.',
  验证码请求: 'Code requests',
  邮件服务已接收: 'Accepted by email provider',
  发信失败: 'Send failed',
  发送状态未知: 'Send status unknown',
  邮箱验证成功: 'Email verifications',
  账号创建事件: 'Account creation events',
  '账号统计暂不可用，请稍后刷新。': 'Account analytics is unavailable. Please refresh shortly.',
  从试用到持续使用: 'From trial to continued use',
  刷新账号数据: 'Refresh account data',
  '独立统计已验证邮箱账号。下方筛选只作用于本区，不与浏览器、爬虫或渠道访问量混算。':
    'Verified email accounts are measured separately. These filters apply only to this section, independently of browser, crawler and referral traffic.',
  观察区间: 'Observation period',
  最近: 'Last ',
  注册时的语言: 'Language at registration',
  全部语言: 'All languages',
  中文: 'Chinese',
  包含标记为测试的账号: 'Include accounts marked as tests',
  '正在读取账号数据…': 'Loading account data…',
  '账号统计尚未启用；暂不显示为 0。': 'Account analytics is not enabled. No zero values are substituted.',
  验证注册: 'Verified sign-ups',
  '所选区间新建账号，含关闭统计的账号': 'New accounts in this period, including analytics opt-outs',
  可测量账号: 'Measurable accounts',
  已允许使用统计的新账号: 'New accounts with measurement enabled',
  首次有效保存: 'First valid save',
  '可测量账号中，注册 24 小时内保存有效结果':
    'Measurable accounts that saved a valid result within 24 hours of signing up',
  旧记录导入账号: 'Accounts importing older records',
  '导入单列，不代替激活': 'Imports are counted separately from activation',
  统计版本: 'Measurement version ',
  '· Asia/Shanghai · 可测量覆盖': ' · Asia/Shanghai · measurable coverage ',
  暂无注册样本: 'No sign-up sample yet',
  包含: 'Including',
  排除: 'Excluding',
  个测试账号: ' test accounts',
  完成试用的游客: 'Guests completing a trial',
  '首次完成在观察区间内；有服务端凭据且允许统计':
    'First completion falls in this period; requires a server receipt and measurement enabled',
  '7 天内注册 / 保存': 'Registered / saved within 7 days',
  激活后再次使用: 'Used again after activation',
  '注册队列中，激活后又完成新操作的账号':
    'Accounts in the sign-up cohort completing a new operation after activation',
  跨浏览器实例继续: 'Continued in another browser instance',
  '注册队列中，在另一实例读回旧记录并完成新操作；不等于设备数':
    'Accounts in the sign-up cohort that retrieved an older record and completed a new operation in another instance; not a device count',
  '这个区间还没有新注册账号。': 'No new accounts in this period.',
  '按激活日分组的回访 · 只看完成观察期的账号':
    'Returns grouped by activation date · only accounts with a complete observation window',
  观察窗口: 'Observation window',
  成熟样本: 'Mature sample',
  完成新操作: 'Completed a new operation',
  回访率: 'Return rate',
  第: 'Day ',
  尚无成熟样本: 'No mature sample yet',
  '口径、覆盖范围与邮件发送': 'Definitions, coverage and email delivery',
  '首次有效保存须有服务端结果凭据。注册前 7 天内的有效试用结果可计入，旧浏览器记录导入不可计入。回访要求完成一次新操作，不把打开页面或查看历史算作使用。':
    'First valid saves require a server result receipt. Valid trials completed within seven days before registration can count; imported older browser records cannot. A return requires a new completed operation, not a pageview or history lookup.',
  '注册与激活各自按所选滚动区间取队列；回访使用激活日后的上海时间自然日。曲线按注册日分组；邮件计数按上海自然日。删除账号会从这些实时分组中移除。关闭统计的账号不进入激活或回访分母，未成熟样本不显示为 0%。“邮箱验证成功”是验证次数，可能包含同一账号的再次登录。':
    'Sign-up and activation cohorts use the selected rolling window. Returns use Shanghai calendar days after activation. The chart groups by sign-up date; email counts use Shanghai dates. Deleted accounts leave these live cohorts. Opted-out accounts are excluded from activation and return denominators. Immature samples are not displayed as 0%. Email verifications count successful checks and can include repeat sign-ins.',
  '邮件服务已接收不代表邮件进了收件箱。目前未将收件箱投递率列为已知指标。统计关闭期间的操作不会在重新开启后补算；跨实例使用独立随机标识，不与匿名访问标识关联。':
    'Provider acceptance does not prove inbox delivery; inbox delivery rate is not a known metric here. Actions during an opt-out are not backfilled. Cross-instance use relies on separate random identifiers, without linking them to anonymous traffic IDs.',
  搜索爬虫请求: 'Search crawler requests',
  'AI 抓取 / Agent 请求': 'AI crawler / Agent requests',
  浏览器页面浏览: 'Browser pageviews',
  访问浏览器标识: 'Visiting browser IDs',
  访问会话: 'Visit sessions',
  成功计算: 'Successful calculations',
  '问卜 Agent 完成': 'Completed Wenbu Agent turns',
  服务错误: 'Service errors',
  搜索爬虫: 'Search crawler',
  'AI 抓取': 'AI crawler',
  '用户委托 Agent': 'User-directed Agent',
  其他自动化: 'Other automation',
  工具客户端: 'Tool client',
  '旧数据 · 无分类依据': 'Legacy · no classification evidence',
  网页浏览: 'Web browsing',
  搜索检索: 'Search retrieval',
  训练抓取: 'Training crawl',
  用户委托抓取: 'User-directed retrieval',
  'UA 自报 · 未核实身份': 'User-agent claim · unverified',
  '浏览器特征 · 不等于真人': 'Browser signal · not proof of a person',
  '协议 / 客户端自报': 'Protocol / client claim',
  'Cloudflare 已验证自动化': 'Cloudflare-verified automation',
  'Cloudflare 已验证签名 Agent': 'Cloudflare-verified signed Agent',
  'Cloudflare 自动化评分推断': 'Inferred from Cloudflare bot score',
  '网页 HTML': 'HTML page',
  'Markdown 手册': 'Markdown guide',
  'JSON 内容': 'JSON content',
  发现文件: 'Discovery file',
  浏览器事件: 'Browser event',
  无头浏览器: 'Headless browser',
  脚本客户端: 'Script client',
  未识别自动化: 'Unidentified automation',
  'Cloudflare 已验证 Bot': 'Cloudflare-verified bot',
  'Cloudflare 签名 Agent': 'Cloudflare-signed Agent',
  'MCP 客户端': 'MCP client',
  'CLI 客户端': 'CLI client',
  'API 客户端': 'API client',
  百度: 'Baidu',
  'ChatGPT 引荐': 'ChatGPT referral',
  'Perplexity 引荐': 'Perplexity referral',
  'Claude 引荐': 'Claude referral',
  'DeepSeek 引荐': 'DeepSeek referral',
  微博: 'Weibo',
  小红书: 'Xiaohongshu',
  邮件通讯: 'Newsletter',
  页面离开: 'Page exit',
  调整设置: 'Setting changed',
  打开反馈: 'Feedback opened',
  '停留超过 30 秒': 'Stayed over 30 seconds',
  阅读深度: 'Reading depth',
  开始工具: 'Tool started',
  展示结果: 'Result received',
  '请求 AI 解读': 'AI reading requested',
  '展示 AI 解读': 'AI reading received',
  '开始 Agent 回合': 'Agent turn started',
  '接收 Agent 结果': 'Agent result received',
  '停止 Agent': 'Agent stopped',
  '旧版：打开引导': 'Legacy: guide opened',
  '旧版：引导步骤': 'Legacy: guidance step',
  '旧版：跳过引导': 'Legacy: guide skipped',
  '旧版：生成问题草稿': 'Legacy: question draft created',
  选择建议: 'Suggestion selected',
  打开成果: 'Artifact opened',
  导出报告: 'Report exported',
  导出对话: 'Conversation exported',
  '导出给 Agent': 'Agent context exported',
  导出手记: 'Journal exported',
  保存手记: 'Journal saved',
  打开上下文: 'Context opened',
  查看卡牌: 'Card inspected',
  打开来源: 'Source opened',
  开始填写: 'Form started',
  客户端错误: 'Client error',
  计算完成: 'Calculation completed',
  解读完成: 'Reading completed',
  'Agent 回合终态': 'Agent turn outcome',
  'Agent 工具阶段': 'Agent tool stage',
  服务请求未完成: 'Service request incomplete',
  'MCP 调用终态': 'MCP call outcome',
  公开内容请求: 'Public content request',
  浏览器标识: 'Browser ID',
  '官方 MCP Registry': 'Official MCP Registry',
  开源接入推广: 'Open-source campaign',
  第一次使用: 'First reading',
  全部请求与事件: 'All requests and events',
  新分类浏览器: 'Newly classified browsers',
  '已识别自动化 / 工具': 'Identified automation / tools',
  功能事件: 'Feature events',
  '无已知来源（含直接访问）': 'No known source (including direct)',
  站内来源: 'Internal referral',
  其他: 'Other',
  未知: 'Unknown',
  未指定: 'Unspecified',
  手机: 'Mobile',
  电脑: 'Desktop',
  平板: 'Tablet',
  自动化访问: 'Automated visit',
  自然搜索: 'Organic search',
  引荐: 'Referral',
  社交: 'Social',
  邮件: 'Email',
  付费点击: 'Paid click',
  'AI 引荐': 'AI referral',
  网页: 'Web',
  八字: 'Bazi',
  易经: 'I Ching',
  塔罗: 'Tarot',
  紫微: 'Zi Wei',
  'AI 解读': 'AI reading',
  探索: 'Explore',
  研究: 'Research',
  已完成: 'Complete',
  等待补充: 'Awaiting input',
  额度限制: 'Quota limit',
  用户中断: 'User cancelled',
  超时: 'Timeout',
  限流: 'Rate limited',
  输入未通过: 'Invalid input',
  服务不可用: 'Service unavailable',
  '次 GET': 'GET requests',
  '服务端记录的公开内容 GET；含爬虫、未知客户端和错误响应，HEAD 单列。':
    'Server-recorded public content GETs, including crawlers, unknown clients and error responses. HEAD requests are listed separately.',
  '被识别为搜索爬虫的公开内容 GET；身份可信度查看分类依据。':
    'Public content GETs classified as search crawlers. See classification evidence for identity confidence.',
  'AI 抓取和用户委托 Agent 获取公开内容；与问卜 Agent 产品回合分开。':
    'Public content fetched by AI crawlers and user-directed Agents, separate from Wenbu Agent product turns.',
  次调用: 'calls',
  '每个 API 操作或 MCP tools/call 的终态一次；包括解析前拒绝的服务请求，不含 MCP 初始化/工具列表和 Agent 内部工具阶段。':
    'One final outcome per API operation or MCP tools/call, including service requests rejected before parsing. Excludes MCP initialization, tool listings and internal Agent tool stages.',
  '次 PV': 'pageviews',
  '浏览器客户端上报的页面浏览；旧记录兼容非 bot、非 edge。脚本阻止、退出或丢报可能造成缺失。':
    'Pageviews reported by browser clients, including legacy non-bot, non-edge events. Script blocking, opt-outs and dropped reports can cause gaps.',
  个浏览器标识: 'browser IDs',
  '发生 PV 的去重匿名浏览器标识，有效期 30 天；不是自然人数，换浏览器、清存储会重复。':
    'Unique anonymous browser IDs with a pageview, valid for 30 days. These are not people; another browser or cleared storage creates another ID.',
  个会话: 'sessions',
  '发生 PV 的去重会话标识；30 分钟不活跃后产生新会话。':
    'Unique session IDs with a pageview. Thirty minutes of inactivity starts a new session.',
  '服务器确认完成非示例计算、解读或问卜 Agent 回合的去重浏览器标识；仅统计可关联标识的浏览器流量。':
    'Unique browser IDs with a server-confirmed non-example calculation, reading or Wenbu Agent completion. Includes only browser traffic with linked IDs.',
  次计算: 'calculations',
  '服务器确认完成的非示例计算；包含网站、API、CLI、MCP，不等于人数。':
    'Server-confirmed non-example calculations across the website, API, CLI and MCP. Not a count of people.',
  个回合: 'turns',
  '问卜 Agent 成功完成的回合；等待补充、额度不足、中断单列，不代表一段完整对话。':
    'Successfully completed Wenbu Agent turns. Waiting for input, quota limits and cancellations are separate. A turn is not a whole conversation.',
  次错误: 'errors',
  '服务终态为 error、unavailable、timeout；输入错误、限速和主动中断单列。':
    'Service outcomes of error, unavailable or timeout. Invalid inputs, rate limits and user cancellations are separate.',
  '查看全部 {0} 项': 'Show all {0}',
  '读取或保存失败（{0}），请检查筛选条件后重试。':
    'Could not load or save ({0}). Check your filters and try again.',
  ' 快照截至 {0}；点击回到最新可刷新快照。': ' Snapshot as of {0}. Choose Latest records to refresh.',
  '{0} 个自然日（含今天）': '{0} calendar days (including today)',
  '最近 {0} 天': 'Last {0} days',
  '本页 {0} 条 · {1}': '{0} records on this page · {1}',
  '{0} · {1}': '{0} · {1}',
  '{0} 条事件': '{0} events',
  '同一批游客；{0} 个已完成 7 天观察期':
    'Same guest cohort; {0} have completed the seven-day observation window',
  '第 {0} 天': 'Day {0}',
  保存邀请可见: 'Save offer visible',
  点击保存邀请: 'Save offer clicked',
  关闭保存邀请: 'Save offer dismissed',
  打开账号面板: 'Account panel opened',
  请求邮箱验证码: 'Email code requested',
  页头账号入口: 'Header account entry',
  结果后的保存邀请: 'Post-result save offer',
  主动保存到账号: 'Explicit account save',
  历史记录账号入口: 'History account entry',
  '1 天': '1 day',
  '{0} 天': '{0} days',
  '最近 1 天': 'Last day',
  '1 个自然日（含今天）': 'Today',
  收到计算结果: 'Calculation result received',
  '收到 AI 解读': 'AI reading received',
  '。': '.',
  '：': ': ',
};
