import type { UsageGate } from './quota';
import type { DeletionLedger } from './deletion-ledger';
export interface Env {
  ASSETS: Fetcher;
  USERDATA?: D1Database;
  AUTH_SECRET?: string;
  ACCOUNT_DATA_KEY?: string;
  AUTH_EMAIL?: SendEmail;
  AUTH_EMAIL_FROM?: string;
  AUTH_EMAIL_DAILY_LIMIT?: string;
  ACCOUNTS_ENABLED?: string;
  ACCOUNTS_MAINTENANCE?: string;
  PRIVACY_LEDGER?: DurableObjectNamespace<DeletionLedger>;
  ANALYTICS?: D1Database;
  ANALYTICS_ARCHIVE?: R2Bucket;
  ANALYTICS_ADMIN_TOKEN?: string;
  ANALYTICS_LIMITER?: RateLimit;
  FEEDBACK_LIMITER?: RateLimit;
  ADMIN_LIMITER?: RateLimit;
  QUOTA: DurableObjectNamespace<UsageGate>;
  RATE_LIMITER?: RateLimit;
  DEEPSEEK_API_KEY?: string;
  QUOTA_SALT?: string;
  SITE_URL: string;
  DEEPSEEK_MODEL: string;
  AI_DAILY_LIMIT: string;
  AI_PER_USER_DAILY_LIMIT: string;
  AGENT_PER_USER_DAILY_LIMIT?: string;
  AGENT_GLOBAL_DAILY_LIMIT?: string;
  AI_NETWORK_DAILY_LIMIT?: string;
  AGENT_NETWORK_DAILY_LIMIT?: string;
}
